# Generated by Django 2.1.1 on 2018-10-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20180930_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='free_text_review',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
