# Generated by Django 2.1.1 on 2018-10-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_review_free_text_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mincepie',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mincepie',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_by',
        ),
    ]
