# Generated by Django 2.1.2 on 2018-10-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_auto_20181007_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='free_text_review',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
