# Generated by Django 2.1.2 on 2018-10-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_auto_20181017_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='free_text_review',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
