# Generated by Django 2.1.2 on 2018-11-12 22:59

from django.db import migrations, models
import rate.models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_auto_20181017_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='mincepie',
            name='box_photo',
            field=models.FileField(blank=True, upload_to=rate.models.box_image_path),
        ),
        migrations.AddField(
            model_name='mincepie',
            name='mince_pie_photo',
            field=models.FileField(blank=True, upload_to=rate.models.mince_pie_image_path),
        ),
    ]
