# Generated by Django 2.1.2 on 2018-11-15 15:05

from django.db import migrations, models
import rate.models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0009_auto_20181112_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='mincepie',
            name='box_back_image',
            field=models.FileField(blank=True, upload_to=rate.models.box_image_path),
        ),
        migrations.AddField(
            model_name='mincepie',
            name='box_back_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
